apiVersion: v1
kind: Service
metadata:
  name: {{ include "kv-responder.fullname" . }}
  labels:
    {{- include "kv-responder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: discovery
      protocol: UDP
      name: discovery
  selector:
    {{- include "kv-responder.selectorLabels" . | nindent 4 }}
    ingress-group: {{ .Values.tenant }}