{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kv-responder.fullname" . }}
  labels:
    {{- include "kv-responder.labels" . | nindent 4 }}
    tenant: {{ .Values.tenant }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kv-responder.selectorLabels" . | nindent 6 }}
      ingress-group: {{ .Values.tenant }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
    relabelings:
      # Add tenant label to all metrics
      - sourceLabels: []
        targetLabel: tenant
        replacement: {{ .Values.tenant }}
      # Add namespace label
      - sourceLabels: [__meta_kubernetes_namespace]
        targetLabel: namespace
      # Add pod name label
      - sourceLabels: [__meta_kubernetes_pod_name]
        targetLabel: pod
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}